apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-restore-pvc
  namespace: app-restore-test
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-restore-service
  namespace: app-restore-test
spec:
  selector:
    app: postgres-restore
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-restore-deployment
  namespace: app-restore-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-restore
  template:
    metadata:
      labels:
        app: postgres-restore
    spec:
      containers:
      - name: postgres
        image: postgres:15-alpine
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_DB
          value: "postgres"
        - name: POSTGRES_USER
          value: "postgres"
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_PASSWORD
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: postgres-storage
        persistentVolumeClaim:
          claimName: postgres-restore-pvc
